// NexusKey - Sciter Archive Resource Binding
// SPDX-License-Identifier: GPL-3.0-only
//
// This file includes the packfolder-generated resources and provides
// a single binding function. Only include resources.cpp here to avoid
// multiple definition linker errors.

#include "sciter-x-api.h"
#include "sciter-x-host-callback.h"

#ifdef SCITER_USE_PACKFOLDER
// Include packfolder-generated resources (Release only)
#include "../resources.cpp"
#endif

namespace NextKey {

// Bind embedded resources to Sciter archive
// Call this ONCE after SciterSetOption and before creating any Sciter windows
void BindSciterResources() {
#ifdef SCITER_USE_PACKFOLDER
    // 'resources' is the byte array generated by packfolder.exe
    sciter::archive::instance().open(aux::elements_of(resources));
#endif
}

}  // namespace NextKey
